- name: Hello World Sample
  hosts: all
  tasks:
   - name: Echo emre
     shell: echo '{"emre":"yardımcı","erdem":"yavuz"}'
     register: shell_result
     become: true
   - debug: msg="{{ shell_result.stdout | from_json}}"